services:
  infra_postgres_multi:
    build:
      context: .docker/postgres
    labels:
      project: "infrastructure"
      service: "multidatabase"
    ports:
      - "3400:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: dummy
      POSTGRES_USER: dummy
      POSTGRES_PASSWORD: ThisIsLocal-NoNeed2Worry!
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dummy -d dummy"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - infra_postgres_multi_data:/var/lib/postgresql/data
      - ./.docker/postgres/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - infra_net

  infra_sonar:
    build:
      context: .docker/sonarqube
    labels:
      project: "infrastructure"
      service: "sonarqube"
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://infra_postgres_multi:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: ThisIsLocal-NoNeed2Worry!
    restart: unless-stopped
    depends_on:
      infra_postgres_multi:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/status || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 10
    volumes:
      - infra_sonarqube_data:/opt/sonarqube/data
      - infra_sonarqube_extensions:/opt/sonarqube/extensions
      - infra_sonarqube_logs:/opt/sonarqube/logs
    networks:
      - infra_net

  infra_keycloak:
    build:
      context: .docker/keycloak
    labels:
      project: "infrastructure"
      service: "keycloak"
      database: "keycloak"
    ports:
      - "4000:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://infra_postgres_multi:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ThisIsLocal-NoNeed2Worry!
      KEYCLOAK_ADMIN: keycloakadm
      KEYCLOAK_ADMIN_PASSWORD: ThisIsLocal-NoNeed2Worry!
    command: start-dev
    depends_on:
      infra_postgres_multi:
        condition: service_healthy
    healthcheck:
      # test: ["CMD-SHELL", "curl -f http://localhost:8080/ || exit 1"]
      test: ["CMD-SHELL", "echo > /dev/tcp/localhost/8080"]
      interval: 30s
      timeout: 20s
      retries: 10
    volumes:
      - infra_keycloak_data:/opt/keycloak/data
    networks:
      - infra_net

volumes:
  infra_postgres_multi_data:
  infra_sonarqube_data:
  infra_sonarqube_extensions:
  infra_sonarqube_logs:
  infra_keycloak_data:

networks:
  infra_net:
    driver: bridge