services:
  sonarqube:
    build: 
      context: .docker/sonarqube
    container_name: sonarqube
    ports:
      - "9000:9000"
    depends_on:
      - postgres_sonar
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgres_sonar:3500/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=thisislocal-noneedtoworry
    volumes:
      - .docker/sonarqube/sonarqube_data:/opt/sonarqube/data
      - .docker/sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
      - .docker/sonarqube/sonarqube_logs:/opt/sonarqube/logs

# Note: postgres_sonar is defined in ../postgres/docker-compose.yml